server.port=8082
spring.application.name=doctor-service
<<<<<<< HEAD


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
=======
<<<<<<< HEAD


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
=======
>>>>>>> 60734b414b21756590b8a37c911cd61c36be28e0
>>>>>>> 9e9fc3733de9b2de3f2956d5953e68387de4487a
